name: PR CI
run-name: "CI pipeline for PR - (#${{ github.event.number }}) ${{ github.event.pull_request.title }}"

permissions:
  contents: read
  actions: read


on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review
    branches: ['master']

jobs:
  pr_ci_wrkflw:
    name: Run CI
    uses: zscaler/terraform-modules-zscaler-ci-workflows/.github/workflows/pr_ci.yml@v1.0.0
    secrets: inherit
    with:
      cloud: azure
      tf_version: 1.2 1.3 1.4
